export default [
    {
        "id":1,
        "name":"系统管理",
        "url":null,
        "perms":null,
        "type":0,
        "icon":"el-icon-setting",
        "level":0,
        "children":[
            {
                "name":"table",
                "url":'TestTable',
                "perms":"",
                "type":2,
                "icon":null,
                "level":1,
                "children":[]
            },
            {
                "name":"新增",
                "url":'HelloWorld',
                "perms":"",
                "type":2,
                "icon":null,
                "level":1,
                "children":[]
            },
            {
                "name":"frameTest",
                "url":'baidu',
                "iframe_url":"http://baidu.com",
                "perms":"",
                "type":2,
                "icon":null,
                "level":1,
                "children":[]
            },
        ]
    },
];
